apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hello-world-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: AppProject for basic hello world app
  sourceRepos:
    - "https://github.com/adamj99/argo-hello-world"
  destinations:
    - namespace: hello-world
      name: in-cluster
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: hello-world-app
  source:
    path: resources/apps/
    repoURL: https://github.com/adamj99/argo-hello-world.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: charts/argo-cd/
    repoURL: https://github.com/adamj99/argo-hello-world.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
